name: Create Hono App

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  create-hono-app:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Create T3 app
        run: bun create next-app@latest --yes test-app

      - name: Install dependencies
        run: |
          cd test-app
          bun install

      - name: Run build
        run: |
          cd test-app
          bun run build

      - name: Run Dev
        run: |
          cd test-app
          bun run dev
